name: publish to hex.pm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-24.04
    container:
      image: erlang:27.3-alpine
    steps:
    - name: Prepare
      run: |
           apk update
           apk --no-cache -u add git
    - uses: actions/checkout@v4
    - name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
           rebar3 ex_doc
           rebar3 hex publish -r hexpm --yes
