name: review

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - main
      - 'stable/**'
      - 'feature/**'

jobs:
  code-style-review:
    runs-on: ubuntu-24.04
    container: erlang:28-alpine
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -
        name: install dependencies
        run: |
          apk --no-cache -u add git emacs-nox
      -
        name: git special configs
        run: |
          git config --global --add safe.directory /__w/enats/enats
      -
        name: Check out repository
        uses: actions/checkout@v4
        with:
          # GitHub pull_request_target Actions works on the target branch,
          # this is used to prevent a PR to alter the workflow itself
          # we therefore have to checkout the head ref of the PR explicitly
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      -
        name: format
        run: rebar3 fmt
      -
        name: automated review
        uses: googleapis/code-suggester@v4
        with:
          command: review
          pull_number: ${{ github.event.pull_request.number }}
          git_dir: '.'
      -
        name: check
        run: git diff --quiet --exit-code
